//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public int IDEstado { get; set; }
        public int IDPais { get; set; }
        public string Estado1 { get; set; }
        public string Sigla { get; set; }
    }
}
